### ISSUE TITLE
JS/Wasm Support

### ISSUE THREAD

**Issue by Skaldebane** [adamglin0/compose-shadow#24]
Hi! Thanks for the great library.

As the shadow implementation on Desktop/iOS is using Skiko, it should be possible to make it work on web targets without modifications.

When I find some time, I'll open PRs to:
- [x] Merge desktop and iOS targets into a single `skikoMain` target, since they're identical. (#27)
- [ ] Add JS and Wasm to build-script (also under `skikoMain`). (#28)
- [ ] Add JS/Wasm to samples (#28)
- [ ] Update README.
